### ISSUE TITLE
Implement Subtract function

### ISSUE THREAD

**Issue by junkyn** [Research-Mini/four-arithmetic-operations#2]
### Description
Implement Subtract function for four arithmetic operations

### To-Do
- [ ] Input two argument fom user 
- [ ] save input number to A, B
- [ ] set C = 0
- [ ] if ( A > B )  
- [ ] for( C 0 to A, C++ ), if ( B + C ) == A , break
- [ ] return C
- [ ] else if ( A < B )
- [ ] for( C 0 to B, C++), if(A+C) == B, break
- [ ] return -C
